# Generated by Django 3.0.6 on 2020-07-06 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posthog', '0067_team_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamBilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=128)),
                ('stripe_checkout_session', models.CharField(blank=True, max_length=128)),
                ('should_setup_billing', models.BooleanField(default=False)),
                ('billing_period_ends', models.DateTimeField(blank=True, default=None, null=True)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posthog.Team')),
            ],
        ),
    ]
