# Generated by Django 3.0.7 on 2020-08-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teambilling',
            name='custom_price_id',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
