# Generated by Django 3.0.7 on 2020-09-07 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multi_tenancy', '0002_teambilling_price_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('default_should_setup_billing', models.BooleanField(default=False)),
                ('price_id', models.CharField(blank=True, default='', max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='teambilling',
            name='price_id',
        ),
        migrations.AddField(
            model_name='teambilling',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='multi_tenancy.Plan'),
        ),
    ]
