# Generated by Django 3.0.7 on 2020-09-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_tenancy', '0003_auto_20200907_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='custom_setup_billing_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teambilling',
            name='checkout_session_created_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price_id',
            field=models.CharField(max_length=128),
        ),
    ]
