# Generated by Django 3.0.7 on 2020-09-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_tenancy', '0005_organizationbilling'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='event_allowance',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='self_serve',
            field=models.BooleanField(default=False),
        ),
    ]
