# Generated by Django 3.0.6 on 2020-12-06 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multi_tenancy', '0006_auto_20200925_0921'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamBilling',
        ),
    ]
