# Generated by Django 3.0.11 on 2021-03-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_tenancy', '0009_human_price_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationbilling',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
