# Generated by Django 3.0.11 on 2021-04-15 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("multi_tenancy", "0010_organizationbilling_stripe_subscription_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationbilling",
            name="billing_period_ends",
            field=models.DateTimeField(
                blank=True, help_text="Final date until when this plan will be active.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="organizationbilling",
            name="should_setup_billing",
            field=models.BooleanField(
                default=False,
                help_text="When this is `True`, the customer will be shown a message prompting them to confirm their billing details on Stripe; should **always be set if the customer hasn't added billing details.** Must be set manually if the plan is manually assigned.",
            ),
        ),
        migrations.AlterField(
            model_name="organizationbilling",
            name="stripe_checkout_session",
            field=models.CharField(
                blank=True,
                help_text="ID of the current checkout session. Only relevant during the setup phase. Use `stripe_subscription_id` afterwards.",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="organizationbilling",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="multi_tenancy.Plan",
            ),
        ),
    ]
